export const colors = {
  primary: '#2563EB',
  'primary-container': '#2563EB',
  'on-primary': '#FFFFFF',
  'on-primary-container': '#FFFFFF',
  secondary: '#22C55E',
  'secondary-container': '#DCFCE7',
  'on-secondary': '#FFFFFF',
  tertiary: '#F59E0B',
  warning: '#F59E0B',
  'warning-container': '#FEF3C7',
  'on-warning-container': '#92400E',
  success: '#22C55E',
  'success-container': '#DCFCE7',
  'on-success-container': '#166534',
  danger: '#EF4444',
  'danger-container': '#FEE2E2',
  'on-danger-container': '#991B1B',
  error: '#EF4444',
  'error-container': '#FEE2E2',
  'on-error': '#FFFFFF',
  background: '#FFFFFF',
  surface: '#FFFFFF',
  'surface-bright': '#FFFFFF',
  'surface-variant': '#F3F4F6',
  'inverse-surface': '#111827',
  'on-inverse-surface': '#FFFFFF',
  'surface-container-lowest': '#FFFFFF',
  'surface-container-low': '#FFFFFF',
  'surface-container': '#F3F4F6',
  'surface-container-high': '#E5E7EB',
  'surface-container-highest': '#E5E7EB',
  'on-surface': '#111827',
  'on-surface-variant': '#1F2937',
  border: '#E5E7EB',
  outline: '#E5E7EB',
  'outline-variant': '#E5E7EB'
}

export default colors
