import React from 'react';
import { Link } from 'react-router-dom';
import { Navbar } from '../components/Navbar';

export function Landing() {
  return (
    <div className="min-h-screen bg-surface">
      <Navbar showUserProfile={false} showLinks={true} />
      <main className="pt-16">
        <section className="relative min-h-[795px] flex items-center justify-center overflow-hidden px-margin-mobile md:px-margin-desktop py-20">
          <div className="absolute inset-0 z-0">
            <div className="absolute top-[-10%] right-[-10%] w-[500px] h-[500px] bg-primary-fixed opacity-20 blur-[100px] rounded-full"></div>
            <div className="absolute bottom-[-10%] left-[-10%] w-[600px] h-[600px] bg-secondary-fixed opacity-10 blur-[120px] rounded-full"></div>
          </div>
          <div className="relative z-10 max-w-container-max mx-auto grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
            <div className="space-y-stack-lg text-center md:text-left">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary font-label-sm text-label-sm border border-primary/20"><span className="material-symbols-outlined text-[18px]">verified_user</span>AI-POWERED MONITORING</div>
              <h1 className="font-headline-xl text-headline-xl text-on-surface leading-tight">Integrity in Every <span className="text-primary">Evaluation.</span></h1>
              <p className="font-body-lg text-body-lg text-on-surface-variant max-w-xl mx-auto md:mx-0">ExamGuard provides a secure, reliable, and user-friendly platform for high-stakes online examinations with real-time AI proctoring and session monitoring.</p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center md:justify-start pt-4"><Link to="/register" className="bg-primary text-white font-bold px-8 py-4 rounded-xl shadow-lg hover:shadow-primary/20 hover:-translate-y-1 transition-all flex items-center justify-center gap-2"><span>Get Started</span><span className="material-symbols-outlined">arrow_forward</span></Link></div>
              <div className="flex items-center justify-center md:justify-start gap-8 pt-8 opacity-60 grayscale hover:grayscale-0 transition-all"><span className="font-label-md text-label-md">Trusted by:</span><div className="flex gap-4"><span className="material-symbols-outlined">school</span><span className="material-symbols-outlined">account_balance</span><span className="material-symbols-outlined">history_edu</span></div></div>
            </div>
            <div className="relative hidden md:block"><div className="absolute -top-10 -right-10 w-64 h-64 bg-primary/10 rounded-full blur-3xl"></div><div className="absolute -bottom-10 -left-10 w-48 h-48 bg-secondary/10 rounded-full blur-3xl"></div><div className="relative bg-white/70 backdrop-blur-md p-6 rounded-[2rem] shadow-2xl border border-white/40"><img className="w-full rounded-2xl shadow-sm object-cover aspect-video" alt="ExamGuard Dashboard" src="https://lh3.googleusercontent.com/aida-public/AB6AXuDif4kfZXmXodNXuG1q5ZFglsvIc3kqB1vJQ-yF6o5asP8K2k6AL4O0sidRB9KTbYJ8nWmwV08aQ1Q3ci1yAFR5B-bSacn1fpGnihG_uTuKuGcD4xNNyKC0OlEB_S1vZhRiykeBwWxXRz0ZwaHoRPoCocfJV6lJumraZZzHLPhwIyNIEfCdLkgxB2M29WHly4RsqLOp6y5ti-qbPx2kreD46TCMTjn4bks4j5my4ybzi07-rnXdfszt8E3dc3XeZopOa9RARxz5UexC" /><div className="absolute -bottom-6 -right-6 bg-white p-4 rounded-2xl shadow-xl border border-outline-variant flex items-center gap-4 animate-bounce"><div className="w-12 h-12 rounded-full bg-green-100 flex items-center justify-center"><span className="material-symbols-outlined text-green-600" style={{ fontVariationSettings: "'FILL' 1" }}>check_circle</span></div><div><p className="font-label-sm text-label-sm text-on-surface-variant">System Integrity</p><p className="font-bold text-primary">100% Verified</p></div></div></div></div>
          </div>
        </section>
        <section className="py-24 bg-surface-container-lowest px-margin-mobile md:px-margin-desktop" id="features"><div className="max-w-container-max mx-auto"><div className="text-center mb-16 space-y-4"><h2 className="font-headline-lg text-headline-lg text-on-surface">Uncompromising Security Features</h2><p className="font-body-md text-body-md text-on-surface-variant max-w-2xl mx-auto">We've built ExamGuard from the ground up to handle the unique challenges of remote academic integrity.</p></div><div className="grid grid-cols-1 md:grid-cols-12 gap-gutter"><div className="md:col-span-8 bg-white p-8 rounded-3xl border border-outline-variant hover:border-primary transition-all shadow-sm"><div className="space-y-4 mb-4"><div className="w-14 h-14 bg-primary/10 text-primary rounded-2xl flex items-center justify-center"><span className="material-symbols-outlined text-3xl">videocam</span></div><h3 className="font-headline-md text-headline-md">Session Monitoring</h3><p className="font-body-md text-on-surface-variant max-w-md">Continuous real-time proctoring with AI-driven gaze tracking, object detection, and noise analysis.</p></div></div><div className="md:col-span-4 bg-primary text-white p-8 rounded-3xl shadow-lg flex flex-col justify-between"><div className="space-y-4"><div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center"><span className="material-symbols-outlined text-2xl" style={{ fontVariationSettings: "'FILL' 1" }}>security</span></div><h3 className="font-headline-md text-headline-md">Secure Authentication</h3><p className="font-body-md text-white/80">Multi-factor identity verification including biometric scans.</p></div></div><div className="md:col-span-4 bg-white p-8 rounded-3xl border border-outline-variant hover:shadow-md transition-all"><div className="w-12 h-12 bg-secondary/10 text-secondary rounded-xl flex items-center justify-center mb-4"><span className="material-symbols-outlined text-2xl">photo_camera</span></div><h3 className="font-headline-md text-headline-md mb-2">Webcam Capture</h3><p className="font-body-md text-on-surface-variant">Automated photo snapshots during the exam to verify presence.</p></div><div className="md:col-span-4 bg-white p-8 rounded-3xl border border-outline-variant hover:shadow-md transition-all"><div className="w-12 h-12 bg-tertiary/10 text-tertiary rounded-xl flex items-center justify-center mb-4"><span className="material-symbols-outlined text-2xl">app_registration</span></div><h3 className="font-headline-md text-headline-md mb-2">Secure Registration</h3><p className="font-body-md text-on-surface-variant">Protected candidate registration with encrypted data storage.</p></div></div></div></section>
        <section id="proctoring" className="py-20 px-margin-mobile md:px-margin-desktop bg-primary text-white"><div className="max-w-container-max mx-auto text-center"><h2 className="font-headline-lg text-headline-lg mb-6">Ready to Transform Your Exams?</h2><p className="font-body-lg text-body-lg text-white/80 max-w-2xl mx-auto mb-10">Join thousands of institutions using ExamGuard for secure and reliable online assessments.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><Link to="/register" className="bg-white text-primary font-bold px-8 py-4 rounded-xl hover:shadow-lg transition-all inline-flex items-center justify-center">Start Your Free Trial</Link><Link to="/login" className="border-2 border-white text-white font-bold px-8 py-4 rounded-xl hover:bg-white/10 transition-all inline-flex items-center justify-center">Login to Existing Account</Link></div></div></section>
        <section className="py-16 px-margin-mobile md:px-margin-desktop bg-surface-container-lowest"><div className="max-w-container-max mx-auto grid grid-cols-1 md:grid-cols-2 gap-8"><div id="privacy"><h2 className="font-headline-md text-headline-md text-on-surface mb-4">Privacy Policy</h2><p className="font-body-md text-body-md text-on-surface-variant">ExamGuard respects your privacy and stores session state locally for prototype testing. No personal information is shared without consent.</p></div><div id="terms"><h2 className="font-headline-md text-headline-md text-on-surface mb-4">Terms of Use</h2><p className="font-body-md text-body-md text-on-surface-variant">By registering, you agree to use ExamGuard for academic assessments only and follow the platform's integrity policies.</p></div></div></section>
      </main>
    </div>
  );
}

export default Landing;
